#define beta RC3

Summary:	Personal publishing platform
Name:		wordpress
Version:	7.0.1%{?beta:~%{beta}}
Release:	1
License:	GPLv2+
Group:		System/Servers
URL:		https://wordpress.org/
Source0:	http://wordpress.org/%{name}-%(echo %{version} |sed -e 's,~,-,g').tar.gz
Source1:	README.install.omv
Requires:	php-mysqli
Requires:	php-mysqlnd
Requires:	php-gd
Requires:	php-imagick
Requires:	php-mbstring
Requires:	php-xml
Requires:	php-dom
Requires:	php-zip
Requires:	php-curl
Requires:	php-intl
Requires:	php-filter
Requires:	php-openssl
Requires:	wordpress-webserver-integration = %{EVRD}
BuildArch:	noarch

%patchlist
wordpress-7.0-config.patch

%description
WordPress is a state-of-the-art, semantic, personal publishing platform with a
focus on aesthetics, Web standards, and usability. It was born out of a desire
for an elegant, well-architectured personal publishing system, and is the
official successor to b2/cafelog. While primarily geared towards functioning
as a Weblog, it is also a flexible CMS capable of managing many types of Web
sites. In addition to the basic Weblog functions, it also has an integrated
link manager (e.g. for blogrolls), XFN support, support for "static" pages,
Atom and RSS feeds for both content and comments, XML-RPC blogging API support
(Blogger, MetaWeblog, and Movable Type APIs), spam blocking features, advanced
cruft-free URL generation, a flexible theme system, and an advanced plugin API.

%package nginx
Summary:	Integration files for running WordPress with the NGINX web server
Group:		System/Servers
Requires:	%{name} = %{EVRD}
Requires:	nginx
Requires:	php-fpm
Provides:	wordpress-webserver-integration = %{EVRD}

%description nginx
Integration files for running WordPress with the NGINX web server

%package apache
Summary:	Integration files for running WordPress with the Apache web server
Group:		System/Servers
Requires:	%{name} = %{EVRD}
Requires:	apache-mod_php
Provides:	wordpress-webserver-integration = %{EVRD}

%description apache
Integration files for running WordPress with the Apache web server

%prep
%autosetup -p1 -n %{name}
# fix dir perms
find . -type d | xargs chmod 755

# fix file perms
find . -type f | xargs chmod 644

# Drop backups generated by autosetup
find . -name "*.*~" |xargs rm -rf

# disable wordpress update option
sed -i -e "s/add_action/#add_action/g" wp-includes/update.php

%build

%install
install -d %{buildroot}%{_sysconfdir}/httpd/conf/webapps.d
install -d %{buildroot}%{_sysconfdir}/%{name}
install -d %{buildroot}/srv/www/%{name}

cp -aRf * %{buildroot}/srv/www/%{name}/

# Activate config and move it to %{_sysconfdir} so it gets backed up
mkdir -p %{buildroot}%{_sysconfdir}/%{name}
cp %{buildroot}/srv/www/%{name}/wp-config-sample.php %{buildroot}%{_sysconfdir}/%{name}/wp-config.php
ln -s ../../..%{_sysconfdir}/%{name}/wp-config.php %{buildroot}/srv/www/%{name}/

# Handle the cron job as a timer so we don't have to make page views trigger it
mkdir -p %{buildroot}%{_unitdir}
cat > %{buildroot}%{_unitdir}/wordpress-cron.service <<'EOF'
[Unit]
Description=Run WordPress Cron Tasks
After=network.target php-fpm.service

[Service]
Type=oneshot
User=www
Group=www
# -f ensures it runs even if WP thinks it is already running
ExecStart=/usr/bin/php /srv/www/wordpress/wp-cron.php -f
WorkingDirectory=/srv/www/wordpress
EOF

cat > %{buildroot}%{_unitdir}/wordpress-cron.timer <<'EOF'
[Unit]
Description=Run WordPress Cron every 5 minutes

[Timer]
OnBootSec=5min
OnUnitActiveSec=5min
Unit=wordpress-cron.service

[Install]
WantedBy=timers.target
EOF


# NGINX integration
mkdir -p %{buildroot}%{_sysconfdir}/php-fpm-instances.d
cat >%{buildroot}%{_sysconfdir}/php-fpm-instances.d/wordpress.conf <<'EOF'
[global]
error_log=syslog

[wordpress]
user=www
group=www
listen=/run/php-fpm/wordpress.sock
listen.owner=www
listen.group=www
listen.mode=0660

; Logging
php_admin_value[error_log]=/var/log/php-fpm/wordpress.log
php_admin_value[log_errors]=on

; Performance tuning
pm=dynamic
pm.max_children=50
pm.start_servers=1
pm.min_spare_servers=1
pm.max_spare_servers=35
pm.max_requests=500

php_admin_value[memory_limit] = 256M
; Be generous -- someone might upload a big 8K video...
php_admin_value[upload_max_filesize] = 10G
php_admin_value[post_max_size] = 10G
; Backup plugins etc. may take a long time
php_admin_value[max_execution_time] = 300
php_admin_value[open_basedir] = /srv/www/%{name}:/tmp
php_admin_value[session.save_path] = /run/php-fpm/sessions/wordpress

php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.interned_string_buffer] = 16
php_admin_value[opcache.max_accelerated_files] = 10000
EOF

mkdir -p %{buildroot}%{_sysconfdir}/nginx/sites-available
cat > %{buildroot}%{_sysconfdir}/nginx/sites-available/wordpress.conf <<'EOF'
upstream phpwordpress {
	server unix:/run/php-fpm/wordpress.sock;
}

server {
	listen 80;
	server_name wordpress.*;

	root /srv/www/%{name};
	index index.php;

	client_max_body_size 10G;
	client_body_timeout 300s;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		fastcgi_pass phpwordpress;
		fastcgi_read_timeout 300;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param HTTPS $https if_not_empty;
	}

	location ~ /\. {
		deny all;
	}
}
EOF

mkdir -p %{buildroot}%{_tmpfilesdir}
cat > %{buildroot}%{_tmpfilesdir}/wordpress.conf <<'EOF'
d /run/php-fpm/sessions/wordpress 0770 www www -
EOF

# Apache integration
cat > %{buildroot}%{_sysconfdir}/httpd/conf/webapps.d/%{name}.conf << EOF

Alias /%{name} /srv/www/%{name}

<Directory /srv/www/%{name}>
    AllowOverride None
    Require all granted

#    Options FollowSymlinks
#    RewriteEngine On
#    RewriteBase /
#    RewriteCond %{REQUEST_FILENAME} !-f
#    RewriteCond %{REQUEST_FILENAME} !-d
#    RewriteRule . /index.php [L]
		    
</Directory>

EOF

# cleanup
rm -f %{buildroot}/var/www/%{name}/license.txt
cp %{SOURCE1} ./README.install.omv

%post
while grep -q 'put your unique phrase here' /srv/www/%{name}/wp-config.php; do
	KEY="$(head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)"
	sed -i "\$H;x;1,/put your unique phrase here/s@put your unique phrase here@${KEY}@;1d" /srv/www/%{name}/wp-config.php
done
systemctl enable --now wordpress-cron.timer
systemctl enable --now php-fpm@wordpress

%preun
if [ "$1" = 0 ]; then
	systemctl disable --now wordpress-cron.timer
	systemctl disable --now php-fpm@wordpress
fi

%files
%doc README.install.omv
%doc license.txt
%{_unitdir}/*.service
%{_unitdir}/*.timer
/srv/www/%{name}
%dir %{_sysconfdir}/%{name}
%config(noreplace) %verify(not md5 size mtime) %{_sysconfdir}/%{name}/wp-config.php

%files nginx
%{_sysconfdir}/php-fpm-instances.d/wordpress.conf
%{_tmpfilesdir}/wordpress.conf
%attr(0644,root,root) %config(noreplace) %verify(not md5 size mtime) %{_sysconfdir}/nginx/sites-available/wordpress.conf

%files apache
%attr(0644,root,root) %config(noreplace) %{_sysconfdir}/httpd/conf/webapps.d/%{name}.conf
